const BUG_REPORT_CONFIG = {

  USE_SERVERLESS_PROXY: true,

  DISCORD_WEBHOOK_URL: '',

  RATE_LIMIT: {
    ENABLED: true,
    MAX_REPORTS_PER_SESSION: 5,      
    COOLDOWN_SECONDS: 60,             
  },

  FALLBACK_TO_MANUAL_COPY: true,      

  SHOW_SUCCESS_MESSAGE: true,

};

window.BUG_REPORT_CONFIG = BUG_REPORT_CONFIG;